USE shadow_commerce;

ALTER TABLE Product
  ADD COLUMN IF NOT EXISTS brand VARCHAR(191) NULL AFTER stock;

CREATE TABLE IF NOT EXISTS Category (
  id VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  sortOrder INT NOT NULL DEFAULT 0,
  isActive BOOLEAN NOT NULL DEFAULT TRUE,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY Category_name_key (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `Order`
  ADD COLUMN IF NOT EXISTS province VARCHAR(191) NULL AFTER address,
  ADD COLUMN IF NOT EXISTS note TEXT NULL AFTER province,
  ADD COLUMN IF NOT EXISTS contactTelegram BOOLEAN NOT NULL DEFAULT FALSE AFTER note,
  ADD COLUMN IF NOT EXISTS paymentMethod VARCHAR(191) NOT NULL DEFAULT 'ABA KHQR' AFTER contactTelegram,
  ADD COLUMN IF NOT EXISTS deliveryFee DECIMAL(10,2) NOT NULL DEFAULT 0 AFTER paymentMethod,
  ADD COLUMN IF NOT EXISTS customerId VARCHAR(191) NULL AFTER status;
